import { WikiQuestion } from '../src/types';

// Systematic, high-quality questions for Hard and Expert difficulty levels (Part 1)
// Calibrated distractors: All 4 options belong to the same era/field/category.
export const curatedHardExpertPart1: WikiQuestion[] = [
  // ================= 1. ВИДЕОИГРЫ (VIDEO GAMES) =================
  {
    id: 'vg-hard-1',
    question: 'Какая студия под руководством Уоррена Спектора разработала культовую киберпанк-игру Deus Ex (2000)?',
    type: 'multiple_choice',
    options: ['Ion Storm', 'Looking Glass Studios', 'Arkane Studios', 'Black Isle Studios'],
    correctAnswer: 'Ion Storm',
    acceptableAnswers: ['Ion Storm', 'Ион Сторм'],
    explanation: 'Остинское отделение Ion Storm создало революционный immersive sim Deus Ex.',
    articleTitle: 'Deus Ex',
    articleUrl: 'https://ru.wikipedia.org/wiki/Deus_Ex',
    difficulty: 'hard',
    category: 'Видеоигры',
    pageviews: 18000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~18k просм/мес)',
  },
  {
    id: 'vg-hard-2',
    question: 'В какой игре 1999 года композитор Акира Ямаока впервые создал своё знаменитое тревожное трип-хоп и индастриал звучание?',
    type: 'multiple_choice',
    options: ['Silent Hill', 'Silent Hill 2', 'Resident Evil 2', 'Alone in the Dark'],
    correctAnswer: 'Silent Hill',
    acceptableAnswers: ['Silent Hill', 'Сайлент Хилл'],
    explanation: 'Акира Ямаока дебютировал в серии в оригинальном Silent Hill (1999) для PlayStation.',
    articleTitle: 'Silent Hill (игра)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Silent_Hill_(игра)',
    difficulty: 'hard',
    category: 'Видеоигры',
    pageviews: 16000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~16k просм/мес)',
  },
  {
    id: 'vg-hard-3',
    question: 'Какой британский разработчик основал студию Bullfrog Productions и создал симуляторы бога Populous и Dungeon Keeper?',
    type: 'multiple_choice',
    options: ['Питер Молиньё', 'Крис Сойер', 'Сид Мейер', 'Джефф Крэммонд'],
    correctAnswer: 'Питер Молиньё',
    acceptableAnswers: ['Питер Молиньё', 'Peter Molyneux', 'Молиньё'],
    explanation: 'Питер Молиньё популяризировал жанр симуляторов бога в студии Bullfrog Productions.',
    articleTitle: 'Молиньё, Питер',
    articleUrl: 'https://ru.wikipedia.org/wiki/Молиньё,_Питер',
    difficulty: 'hard',
    category: 'Видеоигры',
    pageviews: 8500,
    popularityTier: 'medium',
    popularityLabel: 'Средняя популярность (~9k просм/мес)',
  },
  {
    id: 'vg-hard-4',
    question: 'Как звали искусственный интеллект звездолёта «фон Браун» в иммерсивном хорроре System Shock 2?',
    type: 'multiple_choice',
    options: ['SHODAN', 'GLaDOS', 'Кортана', 'AM'],
    correctAnswer: 'SHODAN',
    acceptableAnswers: ['SHODAN', 'Шодан'],
    explanation: 'Злобный искусственный интеллект SHODAN манипулировал игроком в обеих частях System Shock.',
    articleTitle: 'SHODAN',
    articleUrl: 'https://ru.wikipedia.org/wiki/SHODAN',
    difficulty: 'hard',
    category: 'Видеоигры',
    pageviews: 12000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~12k просм/мес)',
  },
  {
    id: 'vg-hard-5',
    question: 'Какая студия создала серию тактических стелс-экшенов Tenchu до того, как прославилась серией Soulsborne?',
    type: 'multiple_choice',
    options: ['FromSoftware', 'Capcom', 'Konami', 'Team Ninja'],
    correctAnswer: 'FromSoftware',
    acceptableAnswers: ['FromSoftware', 'Фром Софтвер'],
    explanation: 'FromSoftware издавала и разрабатывала игры серии Tenchu, а также Armored Core и King\'s Field.',
    articleTitle: 'FromSoftware',
    articleUrl: 'https://ru.wikipedia.org/wiki/FromSoftware',
    difficulty: 'hard',
    category: 'Видеоигры',
    pageviews: 22000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~22k просм/мес)',
  },
  {
    id: 'vg-hard-6',
    question: 'Кто создал движок Build, на котором были созданы классические шутеры Duke Nukem 3D, Blood и Shadow Warrior?',
    type: 'open_ended',
    options: ['Кен Сильверман', 'Джон Кармак', 'Тим Суини', 'Джон Ромеро'],
    correctAnswer: 'Кен Сильверман',
    acceptableAnswers: ['Кен Сильверман', 'Ken Silverman', 'Сильверман'],
    explanation: 'Кен Сильверман разработал движок Build Engine с псевдотрёхмерной секторной геометрией.',
    articleTitle: 'Build (игровой движок)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Build_(игровой_движок)',
    difficulty: 'hard',
    category: 'Видеоигры',
    pageviews: 6500,
    popularityTier: 'medium',
    popularityLabel: 'Средняя популярность (~7k просм/мес)',
  },

  // Expert Видеоигры
  {
    id: 'vg-exp-1',
    question: 'Как звали бессмертного протагониста культовой философской RPG Planescape: Torment (1999)?',
    type: 'multiple_choice',
    options: ['Безымянный (The Nameless One)', 'Избранный (The Chosen One)', 'Серый Страж', 'Потомок Баала'],
    correctAnswer: 'Безымянный (The Nameless One)',
    acceptableAnswers: ['Безымянный', 'The Nameless One', 'Безымянный (The Nameless One)'],
    explanation: 'Протагонист Planescape: Torment просыпается в морге Сигила, забыв свои прошлые реинкарнации.',
    articleTitle: 'Planescape: Torment',
    articleUrl: 'https://ru.wikipedia.org/wiki/Planescape:_Torment',
    difficulty: 'expert',
    category: 'Видеоигры',
    pageviews: 14000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~14k просм/мес)',
  },
  {
    id: 'vg-exp-2',
    question: 'Какая шведская студия разработала в 2002 году сетевой шутер Battlefield 1942 на движке Refractor 2?',
    type: 'multiple_choice',
    options: ['Digital Illusions CE (DICE)', 'Massive Entertainment', 'MachineGames', 'Starbreeze Studios'],
    correctAnswer: 'Digital Illusions CE (DICE)',
    acceptableAnswers: ['Digital Illusions CE', 'DICE', 'Digital Illusions CE (DICE)'],
    explanation: 'DICE совершила прорыв в мультиплеерных шутерах с масштабной техникой в Battlefield 1942.',
    articleTitle: 'DICE (компания)',
    articleUrl: 'https://ru.wikipedia.org/wiki/DICE_(компания)',
    difficulty: 'expert',
    category: 'Видеоигры',
    pageviews: 11000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~11k просм/мес)',
  },
  {
    id: 'vg-exp-3',
    question: 'Кто был главным геймдизайнером и создателем системы ролевых характеристик SPECIAL в оригинальном Fallout (1997)?',
    type: 'multiple_choice',
    options: ['Тим Кейн', 'Крис Авеллон', 'Брайан Фарго', 'Фергюс Уркхарт'],
    correctAnswer: 'Тим Кейн',
    acceptableAnswers: ['Тим Кейн', 'Tim Cain', 'Кейн'],
    explanation: 'Тим Кейн придумал механику SPECIAL и возглавлял разработку оригинального Fallout в Interplay.',
    articleTitle: 'Кейн, Тим',
    articleUrl: 'https://ru.wikipedia.org/wiki/Кейн,_Тим',
    difficulty: 'expert',
    category: 'Видеоигры',
    pageviews: 7000,
    popularityTier: 'medium',
    popularityLabel: 'Нишевая статья (~7k просм/мес)',
  },
  {
    id: 'vg-exp-4',
    question: 'В какой стратегии 1997 года от Cavedog впервые в жанре RTS были применены настоящие 3D-юниты и физика снарядов?',
    type: 'multiple_choice',
    options: ['Total Annihilation', 'Command & Conquer: Tiberian Sun', 'StarCraft', 'Dark Reign'],
    correctAnswer: 'Total Annihilation',
    acceptableAnswers: ['Total Annihilation', 'Тотал Аннигилейшн'],
    explanation: 'Total Annihilation под руководством Криса Тейлора опередила своё время честной 3D-баллистикой.',
    articleTitle: 'Total Annihilation',
    articleUrl: 'https://ru.wikipedia.org/wiki/Total_Annihilation',
    difficulty: 'expert',
    category: 'Видеоигры',
    pageviews: 9500,
    popularityTier: 'medium',
    popularityLabel: 'Нишевая статья (~10k просм/мес)',
  },
  {
    id: 'vg-exp-5',
    question: 'Какой композитор написал знаменитую хоровую тему «One-Winged Angel» для битвы с Сефиротом в Final Fantasy VII?',
    type: 'open_ended',
    options: ['Нобуо Уэмацу', 'Ясунори Мицуда', 'Ёко Симомура', 'Хитоси Сакимото'],
    correctAnswer: 'Нобуо Уэмацу',
    acceptableAnswers: ['Нобуо Уэмацу', 'Nobuo Uematsu', 'Уэмацу'],
    explanation: 'Нобуо Уэмацу — постоянный композитор классических частей Final Fantasy.',
    articleTitle: 'Уэмацу, Нобуо',
    articleUrl: 'https://ru.wikipedia.org/wiki/Уэмацу,_Нобуо',
    difficulty: 'expert',
    category: 'Видеоигры',
    pageviews: 8200,
    popularityTier: 'medium',
    popularityLabel: 'Нишевая статья (~8k просм/мес)',
  },

  // ================= 2. ИСТОРИЯ (HISTORY) =================
  {
    id: 'hist-hard-1',
    question: 'Какой мирный договор 1791 года завершил русско-турецкую войну и закрепил за Россией всё Северное Причерноморье до Днестра?',
    type: 'multiple_choice',
    options: ['Ясский мир', 'Кючук-Кайнарджийский мир', 'Бухарестский мир', 'Андрианопольский мир'],
    correctAnswer: 'Ясский мир',
    acceptableAnswers: ['Ясский мир', 'Ясский мирный договор'],
    explanation: 'Ясский мир 1791 года подтвердил присоединение Крыма и закрепил границу по реке Днестр.',
    articleTitle: 'Ясский мирный договор',
    articleUrl: 'https://ru.wikipedia.org/wiki/Ясский_мирный_договор',
    difficulty: 'hard',
    category: 'История',
    pageviews: 24000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~24k просм/мес)',
  },
  {
    id: 'hist-hard-2',
    question: 'В каком сражении 1812 года ожесточённая битва за мост через реку Лужу заставила Наполеона отступать по Смоленской дороге?',
    type: 'multiple_choice',
    options: ['Сражение под Малоярославцем', 'Бородинское сражение', 'Битва при Красном', 'Тарутинский бой'],
    correctAnswer: 'Сражение под Малоярославцем',
    acceptableAnswers: ['Сражение под Малоярославцем', 'Битва под Малоярославцем', 'Малоярославец'],
    explanation: 'Победа русских войск под Малоярославцем сорвала план Наполеона прорваться в южные губернии.',
    articleTitle: 'Сражение под Малоярославцем',
    articleUrl: 'https://ru.wikipedia.org/wiki/Сражение_под_Малоярославцем',
    difficulty: 'hard',
    category: 'История',
    pageviews: 19000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~19k просм/мес)',
  },
  {
    id: 'hist-hard-3',
    question: 'Какое морское сражение 1571 года флота Священной лиги с Османской империей сломило господство турок на море?',
    type: 'multiple_choice',
    options: ['Битва при Лепанто', 'Битва при Превезе', 'Сражение при Наварине', 'Чесменское сражение'],
    correctAnswer: 'Битва при Лепанто',
    acceptableAnswers: ['Битва при Лепанто', 'Лепанто'],
    explanation: 'Битва при Лепанто в Патрасском заливе стала крупнейшим гребным морским сражением XVI века.',
    articleTitle: 'Битва при Лепанто',
    articleUrl: 'https://ru.wikipedia.org/wiki/Битва_при_Лепанто',
    difficulty: 'hard',
    category: 'История',
    pageviews: 21000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~21k просм/мес)',
  },
  {
    id: 'hist-hard-4',
    question: 'Какая династия правила Китаем с 1368 по 1644 год после свержения монголов и возвела Запретный город в Пекине?',
    type: 'multiple_choice',
    options: ['Династия Мин', 'Династия Цин', 'Династия Сун', 'Династия Тан'],
    correctAnswer: 'Династия Мин',
    acceptableAnswers: ['Династия Мин', 'Мин'],
    explanation: 'Эпоха Мин ознаменовалась расцветом ремёсел, мореплавания Чжэн Хэ и строительством Запретного города.',
    articleTitle: 'Империя Мин',
    articleUrl: 'https://ru.wikipedia.org/wiki/Империя_Мин',
    difficulty: 'hard',
    category: 'История',
    pageviews: 28000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~28k просм/мес)',
  },
  {
    id: 'hist-hard-5',
    question: 'Какой персидский царь VI века до н. э. основал державу Ахеменидов и составил древнейший свод законов на глиняном цилиндре?',
    type: 'open_ended',
    options: ['Кир II Великий', 'Дарий I', 'Ксеркс I', 'Камбис II'],
    correctAnswer: 'Кир II Великий',
    acceptableAnswers: ['Кир II Великий', 'Кир Великий', 'Кир II', 'Cyrus the Great'],
    explanation: 'Кир II Великий объединил Персию и Мидию и захватил Вавилон в 539 г. до н. э.',
    articleTitle: 'Кир II Великий',
    articleUrl: 'https://ru.wikipedia.org/wiki/Кир_II_Великий',
    difficulty: 'hard',
    category: 'История',
    pageviews: 26000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~26k просм/мес)',
  },

  // Expert История
  {
    id: 'hist-exp-1',
    question: 'Какой мирный договор 1648 года завершил Тридцатилетнюю войну и заложил систему суверенных национальных государств?',
    type: 'multiple_choice',
    options: ['Вестфальский мир', 'Пиренейский мир', 'Утрехтский мир', 'Нимвегенский мир'],
    correctAnswer: 'Вестфальский мир',
    acceptableAnswers: ['Вестфальский мир', 'Вестфальский мирный договор'],
    explanation: 'Вестфальский мир 1648 года в Мюнстере и Оснабрюке заложил современный принцип государственного суверенитета.',
    articleTitle: 'Вестфальский мир',
    articleUrl: 'https://ru.wikipedia.org/wiki/Вестфальский_мир',
    difficulty: 'expert',
    category: 'История',
    pageviews: 32000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~32k просм/мес)',
  },
  {
    id: 'hist-exp-2',
    question: 'Какой майордом франков остановил продвижение арабов в Западную Европу в битве при Пуатье в 732 году?',
    type: 'multiple_choice',
    options: ['Карл Мартелл', 'Пипин Короткий', 'Хлодвиг I', 'Карл Великий'],
    correctAnswer: 'Карл Мартелл',
    acceptableAnswers: ['Карл Мартелл', 'Мартелл'],
    explanation: 'Карл Мартелл разбил войско эмира Абдур-Рахмана и создал тяжеловооружённую рыцарскую конницу.',
    articleTitle: 'Карл Мартелл',
    articleUrl: 'https://ru.wikipedia.org/wiki/Карл_Мартелл',
    difficulty: 'expert',
    category: 'История',
    pageviews: 21000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~21k просм/мес)',
  },
  {
    id: 'hist-exp-3',
    question: 'Какой выдающийся полководец императора Юстиниана I разгромил королевство вандалов в Африке и остготов в Италии?',
    type: 'multiple_choice',
    options: ['Велизарий', 'Нарсес', 'Мунд', 'Герман'],
    correctAnswer: 'Велизарий',
    acceptableAnswers: ['Велизарий', 'Флавий Велизарий'],
    explanation: 'Флавий Велизарий вернул под контроль Византийской империи Рим, Карфаген и Равенну.',
    articleTitle: 'Велизарий',
    articleUrl: 'https://ru.wikipedia.org/wiki/Велизарий',
    difficulty: 'expert',
    category: 'История',
    pageviews: 24000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~24k просм/мес)',
  },
  {
    id: 'hist-exp-4',
    question: 'Какое соглашение 1122 года между папой Каликстом II и императором Генрихом V урегулировало спор о праве назначения епископов (инвеституру)?',
    type: 'multiple_choice',
    options: ['Вормсский конкордат', 'Констанцский мир', 'Аугсбургский мир', 'Павийский эдикт'],
    correctAnswer: 'Вормсский конкордат',
    acceptableAnswers: ['Вормсский конкордат', 'Вормсский договор'],
    explanation: 'Вормсский конкордат положил конец затяжной полувековой борьбе за инвеституру.',
    articleTitle: 'Вормсский конкордат',
    articleUrl: 'https://ru.wikipedia.org/wiki/Вормсский_конкордат',
    difficulty: 'expert',
    category: 'История',
    pageviews: 12000,
    popularityTier: 'medium',
    popularityLabel: 'Средняя популярность (~12k просм/мес)',
  },
  {
    id: 'hist-exp-5',
    question: 'Какой древнеиндийский царь династии Маурьев после битвы при Калинге принял буддизм и отверг насилие?',
    type: 'open_ended',
    options: ['Ашока', 'Чандрагупта Маурья', 'Биндусара', 'Канишка'],
    correctAnswer: 'Ашока',
    acceptableAnswers: ['Ашока', 'Ashoka', 'Ашока Великий'],
    explanation: 'Царь Ашока покрыл Индию наскальными эдиктами с принципами терпимости и морали (дхармы).',
    articleTitle: 'Ашока',
    articleUrl: 'https://ru.wikipedia.org/wiki/Ашока',
    difficulty: 'expert',
    category: 'История',
    pageviews: 23000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~23k просм/мес)',
  },

  // ================= 3. НАУКА (SCIENCE) =================
  {
    id: 'sci-hard-1',
    question: 'Какое квантовое явление полного выталкивания магнитного поля из проводника при переходе в сверхпроводящее состояние открыли в 1933 году?',
    type: 'multiple_choice',
    options: ['Эффект Мейснера', 'Эффект Джозефсона', 'Эффект Кондо', 'Эффект Холла'],
    correctAnswer: 'Эффект Мейснера',
    acceptableAnswers: ['Эффект Мейснера', 'Мейснер', 'Эффект Мейснера — Оксенфельда'],
    explanation: 'Эффект Мейснера демонстрирует идеальный диамагнетизм сверхпроводников.',
    articleTitle: 'Эффект Мейснера',
    articleUrl: 'https://ru.wikipedia.org/wiki/Эффект_Мейснера',
    difficulty: 'hard',
    category: 'Наука',
    pageviews: 18000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~18k просм/мес)',
  },
  {
    id: 'sci-hard-2',
    question: 'Какой химический элемент 13-й группы был открыт в 1875 году и подтвердил предсказанный Менделеевым «экаалюминий»?',
    type: 'multiple_choice',
    options: ['Галлий', 'Германий', 'Скандий', 'Индий'],
    correctAnswer: 'Галлий',
    acceptableAnswers: ['Галлий', 'Gallium', 'Ga'],
    explanation: 'Француз Поль Лекок де Буабодран открыл галлий, спектроскопически доказав точность периодического закона.',
    articleTitle: 'Галлий',
    articleUrl: 'https://ru.wikipedia.org/wiki/Галлий',
    difficulty: 'hard',
    category: 'Наука',
    pageviews: 25000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~25k просм/мес)',
  },
  {
    id: 'sci-hard-3',
    question: 'Какой идеальный термодинамический цикл из двух изотерм и двух адиабат обладает максимально возможным КПД?',
    type: 'multiple_choice',
    options: ['Цикл Карно', 'Цикл Ренкина', 'Цикл Отто', 'Цикл Стирлинга'],
    correctAnswer: 'Цикл Карно',
    acceptableAnswers: ['Цикл Карно', 'Карно'],
    explanation: 'Сади Карно в 1824 году сформулировал предельный КПД тепловой машины через отношение температур.',
    articleTitle: 'Цикл Карно',
    articleUrl: 'https://ru.wikipedia.org/wiki/Цикл_Карно',
    difficulty: 'hard',
    category: 'Наука',
    pageviews: 22000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~22k просм/мес)',
  },
  {
    id: 'sci-hard-4',
    question: 'Какой французский учёный разработал метод представления сложных периодических функций в виде тригонометрических рядов?',
    type: 'multiple_choice',
    options: ['Жозеф Фурье', 'Пьер-Симон Лаплас', 'Симеон Дени Пуассон', 'Огюстен Луи Коши'],
    correctAnswer: 'Жозеф Фурье',
    acceptableAnswers: ['Жозеф Фурье', 'Фурье', 'Fourier'],
    explanation: 'Ряды Фурье и преобразование Фурье являются фундаментом цифровой обработки сигналов.',
    articleTitle: 'Фурье, Жозеф',
    articleUrl: 'https://ru.wikipedia.org/wiki/Фурье,_Жозеф',
    difficulty: 'hard',
    category: 'Наука',
    pageviews: 15000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~15k просм/мес)',
  },
  {
    id: 'sci-hard-5',
    question: 'Какая безразмерная величина в гидродинамике характеризует отношение сил инерции к силам вязкости и определяет переход к турбулентности?',
    type: 'open_ended',
    options: ['Число Рейнольдса', 'Число Маха', 'Число Фруда', 'Число Прандтля'],
    correctAnswer: 'Число Рейнольдса',
    acceptableAnswers: ['Число Рейнольдса', 'Рейнольдс', 'Re'],
    explanation: 'Осборн Рейнольдс показал, что при превышении критического числа Re ламинарный поток становится турбулентным.',
    articleTitle: 'Число Рейнольдса',
    articleUrl: 'https://ru.wikipedia.org/wiki/Число_Рейнольдса',
    difficulty: 'hard',
    category: 'Наука',
    pageviews: 24000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~24k просм/мес)',
  },

  // Expert Наука
  {
    id: 'sci-exp-1',
    question: 'Какой верхний предел массы невращающегося белого карлика (~1,44 массы Солнца) рассчитал индийский астрофизик в 1930 году?',
    type: 'multiple_choice',
    options: ['Предел Чандрасекара', 'Предел Оппенгеймера — Волкова', 'Предел Эддингтона', 'Радиус Шварцшильда'],
    correctAnswer: 'Предел Чандрасекара',
    acceptableAnswers: ['Предел Чандрасекара', 'Чандрасекар'],
    explanation: 'Выше предела Чандрасекара давление вырожденного электронного газа не может сдерживать гравитацию.',
    articleTitle: 'Предел Чандрасекара',
    articleUrl: 'https://ru.wikipedia.org/wiki/Предел_Чандрасекара',
    difficulty: 'expert',
    category: 'Наука',
    pageviews: 19000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~19k просм/мес)',
  },
  {
    id: 'sci-exp-2',
    question: 'Какой венгерско-британский физик в 1947 году разработал метод голографии и получил Нобелевскую премию?',
    type: 'multiple_choice',
    options: ['Деннис Габор', 'Лео Силард', 'Юджин Вигнер', 'Эдвард Теллер'],
    correctAnswer: 'Деннис Габор',
    acceptableAnswers: ['Деннис Габор', 'Габор', 'Dennis Gabor'],
    explanation: 'Деннис Габор изобрёл волновой интерференционный метод записи трёхмерного изображения.',
    articleTitle: 'Габор, Деннис',
    articleUrl: 'https://ru.wikipedia.org/wiki/Габор,_Деннис',
    difficulty: 'expert',
    category: 'Наука',
    pageviews: 8500,
    popularityTier: 'medium',
    popularityLabel: 'Нишевая статья (~9k просм/мес)',
  },
  {
    id: 'sci-exp-3',
    question: 'Какое релятивистское волновое уравнение объединило квантовую механику со специальной теорией относительности и предсказало позитрон?',
    type: 'multiple_choice',
    options: ['Уравнение Дирака', 'Уравнение Клейна — Гордона', 'Уравнение Шрёдингера', 'Уравнение Паули'],
    correctAnswer: 'Уравнение Дирака',
    acceptableAnswers: ['Уравнение Дирака', 'Дирак'],
    explanation: 'Поль Дирак в 1928 году вывел релятивистское уравнение для электрона, объяснив спин и антиматерию.',
    articleTitle: 'Уравнение Дирака',
    articleUrl: 'https://ru.wikipedia.org/wiki/Уравнение_Дирака',
    difficulty: 'expert',
    category: 'Наука',
    pageviews: 16000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~16k просм/мес)',
  },
  {
    id: 'sci-exp-4',
    question: 'Какая теорема теоретической физики связывает каждую непрерывную симметрию действия физической системы с законом сохранения?',
    type: 'multiple_choice',
    options: ['Теорема Нётер', 'Теорема Лиувилля', 'Теорема Белла', 'CPT-теорема'],
    correctAnswer: 'Теорема Нётер',
    acceptableAnswers: ['Теорема Нётер', 'Нётер', 'Noether\'s theorem'],
    explanation: 'Эмми Нётер доказала, что симметрия времени даёт сохранение энергии, а трансляционная симметрия — импульса.',
    articleTitle: 'Теорема Нётер',
    articleUrl: 'https://ru.wikipedia.org/wiki/Теорема_Нётер',
    difficulty: 'expert',
    category: 'Наука',
    pageviews: 14000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~14k просм/мес)',
  },
  {
    id: 'sci-exp-5',
    question: 'Какой российский математик доказал гипотезу Пуанкаре о трёхмерных многообразиях с помощью потока Риччи с хирургией?',
    type: 'open_ended',
    options: ['Григорий Перельман', 'Владимир Арнольд', 'Андрей Колмогоров', 'Юрий Манин'],
    correctAnswer: 'Григорий Перельман',
    acceptableAnswers: ['Григорий Перельман', 'Перельман'],
    explanation: 'Григорий Перельман решил одну из задач тысячелетия математики в серии статей 2002–2003 годов.',
    articleTitle: 'Перельман, Григорий Яковлевич',
    articleUrl: 'https://ru.wikipedia.org/wiki/Перельман,_Григорий_Яковлевич',
    difficulty: 'expert',
    category: 'Наука',
    pageviews: 45000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~45k просм/мес)',
  },

  // ================= 4. ГЕОГРАФИЯ (GEOGRAPHY) =================
  {
    id: 'geo-hard-1',
    question: 'Какой пролив между Огненной Землёй и Южными Шетландскими островами соединяет Атлантику с Тихим океаном и является самым широким на Земле?',
    type: 'multiple_choice',
    options: ['Пролив Дрейка', 'Магелланов пролив', 'Берингов пролив', 'Пролив Бигля'],
    correctAnswer: 'Пролив Дрейка',
    acceptableAnswers: ['Пролив Дрейка', 'Дрейк'],
    explanation: 'Ширина пролива Дрейка превышает 800 километров в самом узком месте.',
    articleTitle: 'Пролив Дрейка',
    articleUrl: 'https://ru.wikipedia.org/wiki/Пролив_Дрейка',
    difficulty: 'hard',
    category: 'География',
    pageviews: 31000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~31k просм/мес)',
  },
  {
    id: 'geo-hard-2',
    question: 'Какое африканское рифтовое озеро является вторым по глубине (1470 м) и вторым по объёму пресноводным озером планеты после Байкала?',
    type: 'multiple_choice',
    options: ['Танганьика', 'Виктория', 'Ньяса', 'Альберт'],
    correctAnswer: 'Танганьика',
    acceptableAnswers: ['Танганьика', 'Озеро Танганьика'],
    explanation: 'Танганьика протянулась на 676 километров в рифтовой впадине Восточной Африки.',
    articleTitle: 'Танганьика',
    articleUrl: 'https://ru.wikipedia.org/wiki/Танганьика',
    difficulty: 'hard',
    category: 'География',
    pageviews: 26000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~26k просм/мес)',
  },
  {
    id: 'geo-hard-3',
    question: 'Какой остров является крупнейшим по площади в Средиземном море?',
    type: 'multiple_choice',
    options: ['Сицилия', 'Сардиния', 'Кипр', 'Корсика'],
    correctAnswer: 'Сицилия',
    acceptableAnswers: ['Сицилия', 'Sicily'],
    explanation: 'Площадь Сицилии составляет около 25 700 кв. км, опережая Сардинию (24 090 кв. км).',
    articleTitle: 'Сицилия',
    articleUrl: 'https://ru.wikipedia.org/wiki/Сицилия',
    difficulty: 'hard',
    category: 'География',
    pageviews: 35000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~35k просм/мес)',
  },
  {
    id: 'geo-hard-4',
    question: 'Какой водопад на реке Чурун в Венесуэле является высочайшим водопадом в мире с непрерывным падением почти 1000 метров?',
    type: 'multiple_choice',
    options: ['Анхель', 'Игуасу', 'Виктория', 'Тугела'],
    correctAnswer: 'Анхель',
    acceptableAnswers: ['Анхель', 'Angel Falls'],
    explanation: 'Водопад Анхель низвергается с горы Ауян-Тепуи в тропических джунглях Венесуэлы.',
    articleTitle: 'Анхель',
    articleUrl: 'https://ru.wikipedia.org/wiki/Анхель',
    difficulty: 'hard',
    category: 'География',
    pageviews: 34000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~34k просм/мес)',
  },
  {
    id: 'geo-hard-5',
    question: 'Какой вулкан на Сицилии является самым высоким действующим вулканом в континентальной Европе?',
    type: 'open_ended',
    options: ['Этна', 'Везувий', 'Стромболи', 'Вулькано'],
    correctAnswer: 'Этна',
    acceptableAnswers: ['Этна', 'Etna'],
    explanation: 'Высота Этны превышает 3350 метров и постоянно меняется в результате извержений.',
    articleTitle: 'Этна',
    articleUrl: 'https://ru.wikipedia.org/wiki/Этна',
    difficulty: 'hard',
    category: 'География',
    pageviews: 38000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~38k просм/мес)',
  },

  // Expert География
  {
    id: 'geo-exp-1',
    question: 'Какой арктический архипелаг из 192 островов был открыт экспедицией Юлиуса Пайера и Карла Вейпрехта в 1873 году?',
    type: 'multiple_choice',
    options: ['Земля Франца-Иосифа', 'Северная Земля', 'Новосибирские острова', 'Шпицберген'],
    correctAnswer: 'Земля Франца-Иосифа',
    acceptableAnswers: ['Земля Франца-Иосифа', 'Франц-Иосиф'],
    explanation: 'Австро-венгерская полярная экспедиция на судне «Тегетхофф» случайно открыла этот северный архипелаг.',
    articleTitle: 'Земля Франца-Иосифа',
    articleUrl: 'https://ru.wikipedia.org/wiki/Земля_Франца-Иосифа',
    difficulty: 'expert',
    category: 'География',
    pageviews: 29000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~29k просм/мес)',
  },
  {
    id: 'geo-exp-2',
    question: 'Какая низшая точка суши Северной Америки лежит на отметке 86 метров ниже уровня мирового океана?',
    type: 'multiple_choice',
    options: ['Впадина Бэдуотер (Долина Смерти)', 'Озеро Солтон-Си', 'Лагуна-дель-Карбон', 'Долина Коачелла'],
    correctAnswer: 'Впадина Бэдуотер (Долина Смерти)',
    acceptableAnswers: ['Впадина Бэдуотер', 'Бэдуотер', 'Badwater'],
    explanation: 'Бассейн Бэдуотер в Долине Смерти представляет собой обширный солончак ниже уровня моря.',
    articleTitle: 'Бэдуотер',
    articleUrl: 'https://ru.wikipedia.org/wiki/Бэдуотер',
    difficulty: 'expert',
    category: 'География',
    pageviews: 11000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~11k просм/мес)',
  },
  {
    id: 'geo-exp-3',
    question: 'Какое высокогорное бессточное озеро-солончак в Боливии на высоте 3650 м является крупнейшим в мире солончаком?',
    type: 'multiple_choice',
    options: ['Солончак Уюни', 'Салар-де-Атакама', 'Салар-де-Арисаро', 'Солончак Койпаса'],
    correctAnswer: 'Солончак Уюни',
    acceptableAnswers: ['Солончак Уюни', 'Уюни', 'Salar de Uyuni'],
    explanation: 'Площадь солончака Уюни превышает 10 500 кв. км, и во время сезона дождей он превращается в гигантское зеркало.',
    articleTitle: 'Солончак Уюни',
    articleUrl: 'https://ru.wikipedia.org/wiki/Солончак_Уюни',
    difficulty: 'expert',
    category: 'География',
    pageviews: 27000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~27k просм/мес)',
  },
  {
    id: 'geo-exp-4',
    question: 'Какая столица суверенного государства расположена на наибольшей абсолютной высоте над уровнем моря (около 3640 м)?',
    type: 'multiple_choice',
    options: ['Ла-Пас', 'Кито', 'Богота', 'Тхимпху'],
    correctAnswer: 'Ла-Пас',
    acceptableAnswers: ['Ла-Пас', 'La Paz'],
    explanation: 'Ла-Пас (фактическая столица Боливии) расположен в каньоне на высокогорном плато Альтиплано.',
    articleTitle: 'Ла-Пас',
    articleUrl: 'https://ru.wikipedia.org/wiki/Ла-Пас',
    difficulty: 'expert',
    category: 'География',
    pageviews: 31000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~31k просм/мес)',
  },
  {
    id: 'geo-exp-5',
    question: 'Какая река в Африке дважды пересекает экватор и является второй по полноводности в мире после Амазонки?',
    type: 'open_ended',
    options: ['Конго', 'Нил', 'Нигер', 'Замбези'],
    correctAnswer: 'Конго',
    acceptableAnswers: ['Конго', 'Река Конго', 'Заир'],
    explanation: 'Конго — глубочайшая река мира (глубины местами более 220 метров) с колоссальным водосбором.',
    articleTitle: 'Конго (река)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Конго_(река)',
    difficulty: 'expert',
    category: 'География',
    pageviews: 29000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~29k просм/мес)',
  },

  // ================= 5. КОСМОС (SPACE) =================
  {
    id: 'spc-hard-1',
    question: 'Какой спутник Нептуна обладает ретроградной орбитой (обратным вращением) и действующими азотными криогейзерами?',
    type: 'multiple_choice',
    options: ['Тритон', 'Протей', 'Нереида', 'Ларисса'],
    correctAnswer: 'Тритон',
    acceptableAnswers: ['Тритон', 'Triton'],
    explanation: 'Тритон является единственным крупным спутником в Солнечной системе с обратным движением по орбите.',
    articleTitle: 'Тритон (спутник)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Тритон_(спутник)',
    difficulty: 'hard',
    category: 'Космос',
    pageviews: 27000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~27k просм/мес)',
  },
  {
    id: 'spc-hard-2',
    question: 'Какой потухший щитовой вулкан на Марсе высотой около 22 км является высочайшей горой в Солнечной системе?',
    type: 'multiple_choice',
    options: ['Олимп', 'Гора Павлина', 'Гора Аскрийская', 'Гора Арсия'],
    correctAnswer: 'Олимп',
    acceptableAnswers: ['Олимп', 'Olympus Mons', 'Гора Олимп'],
    explanation: 'Олимп на Марсе возвышается на 22 км и имеет основание диаметром более 500 км.',
    articleTitle: 'Олимп (Марс)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Олимп_(Марс)',
    difficulty: 'hard',
    category: 'Космос',
    pageviews: 39000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~39k просм/мес)',
  },
  {
    id: 'spc-hard-3',
    question: 'Какой космический аппарат NASA, запущенный в 1977 году, первым в истории вышел в межзвёздное пространство за пределы гелиосферы?',
    type: 'multiple_choice',
    options: ['Вояджер-1', 'Пионер-10', 'Вояджер-2', 'Новые горизонты'],
    correctAnswer: 'Вояджер-1',
    acceptableAnswers: ['Вояджер-1', 'Voyager 1', 'Вояджер 1'],
    explanation: 'В августе 2012 года «Вояджер-1» преодолел гелиопаузу и вышел в межзвёздную среду.',
    articleTitle: 'Вояджер-1',
    articleUrl: 'https://ru.wikipedia.org/wiki/Вояджер-1',
    difficulty: 'hard',
    category: 'Космос',
    pageviews: 42000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~42k просм/мес)',
  },
  {
    id: 'spc-hard-4',
    question: 'Какой спутник Юпитера отличается высочайшей вулканической активностью из-за приливного гравитационного трения?',
    type: 'multiple_choice',
    options: ['Ио', 'Европа', 'Ганимед', 'Каллисто'],
    correctAnswer: 'Ио',
    acceptableAnswers: ['Ио', 'Io'],
    explanation: 'На Ио действует более 400 активных вулканов, непрерывно выбрасывающих серу и диоксид серы.',
    articleTitle: 'Ио (спутник)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Ио_(спутник)',
    difficulty: 'hard',
    category: 'Космос',
    pageviews: 33000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~33k просм/мес)',
  },
  {
    id: 'spc-hard-5',
    question: 'Какая планета Солнечной системы имеет аномальный наклон оси вращения около 98 градусов и обращается «лёжа на боку»?',
    type: 'open_ended',
    options: ['Уран', 'Нептун', 'Сатурн', 'Венера'],
    correctAnswer: 'Уран',
    acceptableAnswers: ['Уран', 'Uranus'],
    explanation: 'Уран вращается почти в плоскости своей орбиты, что приводит к экстремальной смене сезонов.',
    articleTitle: 'Уран (планета)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Уран_(планета)',
    difficulty: 'hard',
    category: 'Космос',
    pageviews: 49000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~49k просм/мес)',
  },

  // Expert Космос
  {
    id: 'spc-exp-1',
    question: 'В какой точке гравитационного равновесия системы Солнце — Земля (в 1,5 млн км от Земли) обращается телескоп «Джеймс Уэбб»?',
    type: 'multiple_choice',
    options: ['Точка Лагранжа L2', 'Точка Лагранжа L1', 'Точка Лагранжа L3', 'Точка Лагранжа L4'],
    correctAnswer: 'Точка Лагранжа L2',
    acceptableAnswers: ['Точка Лагранжа L2', 'L2', 'Точка L2'],
    explanation: 'Точка L2 позволяет экранировать инфракрасные инструменты телескопа от тепла Солнца и Земли.',
    articleTitle: 'Точки Лагранжа',
    articleUrl: 'https://ru.wikipedia.org/wiki/Точки_Лагранжа',
    difficulty: 'expert',
    category: 'Космос',
    pageviews: 28000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~28k просм/мес)',
  },
  {
    id: 'spc-exp-2',
    question: 'Какой зонд Европейского космического агентства в 2005 году совершил первую в истории посадку на спутник Титан?',
    type: 'multiple_choice',
    options: ['Гюйгенс', 'Кассини', 'Филы', 'Розетта'],
    correctAnswer: 'Гюйгенс',
    acceptableAnswers: ['Гюйгенс', 'Huygens'],
    explanation: 'Зонд «Гюйгенс» передал снимки метановых речных русел и ледяных дюн с поверхности Титана.',
    articleTitle: 'Гюйгенс (зонд)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Гюйгенс_(зонд)',
    difficulty: 'expert',
    category: 'Космос',
    pageviews: 18000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~18k просм/мес)',
  },
  {
    id: 'spc-exp-3',
    question: 'Какой радиус орбиты спутника определяет границу, ближе которой приливные силы планеты разрушают гравитационно связанное тело?',
    type: 'multiple_choice',
    options: ['Предел Роша', 'Предел Хилла', 'Радиус Шварцшильда', 'Сфера Койпера'],
    correctAnswer: 'Предел Роша',
    acceptableAnswers: ['Предел Роша', 'Предел Роша-Линдблада'],
    explanation: 'Французский астроном Эдуар Рош вычислил радиус разрушения спутников приливными силами в 1848 году.',
    articleTitle: 'Предел Роша',
    articleUrl: 'https://ru.wikipedia.org/wiki/Предел_Роша',
    difficulty: 'expert',
    category: 'Космос',
    pageviews: 22000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~22k просм/мес)',
  },
  {
    id: 'spc-exp-4',
    question: 'Какой советский космический аппарат в октябре 1959 года впервые в истории человечества сфотографировал обратную сторону Луны?',
    type: 'multiple_choice',
    options: ['Луна-3', 'Луна-1', 'Луна-2', 'Луна-9'],
    correctAnswer: 'Луна-3',
    acceptableAnswers: ['Луна-3', 'Луна 3'],
    explanation: '«Луна-3» проявила фотоплёнку на борту и передала фототелевизионный сигнал на Землю.',
    articleTitle: 'Луна-3',
    articleUrl: 'https://ru.wikipedia.org/wiki/Луна-3',
    difficulty: 'expert',
    category: 'Космос',
    pageviews: 24000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~24k просм/мес)',
  },
  {
    id: 'spc-exp-5',
    question: 'Какой гипотетический сферический слой ледяных объектов на дальней периферии Солнечной системы служит источником долгопериодических комет?',
    type: 'open_ended',
    options: ['Облако Оорта', 'Пояс Койпера', 'Рассеянный диск', 'Пояс астероидов'],
    correctAnswer: 'Облако Оорта',
    acceptableAnswers: ['Облако Оорта', 'Оорт', 'Oort cloud'],
    explanation: 'Ян Оорт рассчитал существование кометного облака на расстояниях до одного светового года от Солнца.',
    articleTitle: 'Облако Оорта',
    articleUrl: 'https://ru.wikipedia.org/wiki/Облако_Оорта',
    difficulty: 'expert',
    category: 'Космос',
    pageviews: 31000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~31k просм/мес)',
  },

  // ================= 6. ЛИТЕРАТУРА (LITERATURE) =================
  {
    id: 'lit-hard-1',
    question: 'В каком романе Достоевского повествование ведётся от лица юноши Аркадия Долгорукого, мечтающего о богатстве и духовном могуществе?',
    type: 'multiple_choice',
    options: ['Подросток', 'Игрок', 'Бесы', 'Униженные и оскорблённые'],
    correctAnswer: 'Подросток',
    acceptableAnswers: ['Подросток'],
    explanation: 'Роман «Подросток» (1875) входит в так называемое «великое пятикнижие» Фёдора Достоевского.',
    articleTitle: 'Подросток (роман)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Подросток_(роман)',
    difficulty: 'hard',
    category: 'Литература',
    pageviews: 21000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~21k просм/мес)',
  },
  {
    id: 'lit-hard-2',
    question: 'В каком романе Ивана Гончарова главный герой-эстет Борис Райский приезжает в приволжское поместье своей бабушки Татьяны Марковны?',
    type: 'multiple_choice',
    options: ['Обрыв', 'Обыкновенная история', 'Обломов', 'Фрегат Паллада'],
    correctAnswer: 'Обрыв',
    acceptableAnswers: ['Обрыв'],
    explanation: 'Роман «Обрыв» писался Гончаровым почти двадцать лет и завершил его романную трилогию.',
    articleTitle: 'Обрыв (роман)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Обрыв_(роман)',
    difficulty: 'hard',
    category: 'Литература',
    pageviews: 18000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~18k просм/мес)',
  },
  {
    id: 'lit-hard-3',
    question: 'Кто написал повесть «Поединок» (1905), беспощадно раскрывшую нравы провинциального офицерства царской армии?',
    type: 'multiple_choice',
    options: ['Александр Куприн', 'Иван Бунин', 'Леонид Андреев', 'Максим Горький'],
    correctAnswer: 'Александр Куприн',
    acceptableAnswers: ['Александр Куприн', 'Куприн'],
    explanation: 'Повесть «Поединок» принесла Куприну всероссийскую известность благодаря драме подпоручика Ромашова.',
    articleTitle: 'Поединок (повесть)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Поединок_(повесть)',
    difficulty: 'hard',
    category: 'Литература',
    pageviews: 24000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~24k просм/мес)',
  },
  {
    id: 'lit-hard-4',
    question: 'Какой латиноамериканский писатель создал семейную сагу «Сто лет одиночества» о поколениях рода Буэндиа в Макондо?',
    type: 'multiple_choice',
    options: ['Габриэль Гарсиа Маркес', 'Марио Варгас Льоса', 'Хорхе Луис Борхес', 'Хулио Кортасар'],
    correctAnswer: 'Габриэль Гарсиа Маркес',
    acceptableAnswers: ['Габриэль Гарсиа Маркес', 'Маркес', 'Гарсиа Маркес'],
    explanation: 'Роман Гарсиа Маркеса стал вершиной направления магического реализма в мировой литературе.',
    articleTitle: 'Сто лет одиночества',
    articleUrl: 'https://ru.wikipedia.org/wiki/Сто_лет_одиночества',
    difficulty: 'hard',
    category: 'Литература',
    pageviews: 48000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~48k просм/мес)',
  },
  {
    id: 'lit-hard-5',
    question: 'В какой комедии Дениса Фонвизина выведены образы помещицы Простаковой, её сына Митрофанушки и благородного Стародума?',
    type: 'open_ended',
    options: ['Недоросль', 'Бригадир', 'Горе от ума', 'Ябеда'],
    correctAnswer: 'Недоросль',
    acceptableAnswers: ['Недоросль'],
    explanation: '«Недоросль» — классическая русская сатирическая комедия эпохи Просвещения.',
    articleTitle: 'Недоросль',
    articleUrl: 'https://ru.wikipedia.org/wiki/Недоросль',
    difficulty: 'hard',
    category: 'Литература',
    pageviews: 39000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~39k просм/мес)',
  },

  // Expert Литература
  {
    id: 'lit-exp-1',
    question: 'Кто написал экспрессионистскую антиутопическую повесть «Котлован» (1930) и роман «Чевенгур» об искажённом языке советской эпохи?',
    type: 'multiple_choice',
    options: ['Андрей Платонов', 'Евгений Замятин', 'Борис Пильняк', 'Михаил Зощенко'],
    correctAnswer: 'Андрей Платонов',
    acceptableAnswers: ['Андрей Платонов', 'Платонов'],
    explanation: 'Андрей Платонов создал уникальный по силе язык, отразивший трагедию коллективизации и утопии.',
    articleTitle: 'Котлован (повесть)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Котлован_(повесть)',
    difficulty: 'expert',
    category: 'Литература',
    pageviews: 29000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~29k просм/мес)',
  },
  {
    id: 'lit-exp-2',
    question: 'В каком семитомном романе-эпопее Марселя Пруста вкус печенья «мадлен» в липовом чае воскрешает воспоминания о детстве в Комбре?',
    type: 'multiple_choice',
    options: ['В поисках утраченного времени', 'Под сенью девушек в цвету', 'Сторона Свана', 'Обретённое время'],
    correctAnswer: 'В поисках утраченного времени',
    acceptableAnswers: ['В поисках утраченного времени', 'À la recherche du temps perdu'],
    explanation: '«Эпизод с мадлен» стал хрестоматийным примером непроизвольной психологической памяти.',
    articleTitle: 'В поисках утраченного времени',
    articleUrl: 'https://ru.wikipedia.org/wiki/В_поисках_утраченного_времени',
    difficulty: 'expert',
    category: 'Литература',
    pageviews: 33000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~33k просм/мес)',
  },
  {
    id: 'lit-exp-3',
    question: 'Какой итальянский писатель эпохи Возрождения создал сборник из ста новелл «Декамерон», рассказанных во время чумы во Флоренции?',
    type: 'multiple_choice',
    options: ['Джованни Боккаччо', 'Франческо Петрарка', 'Данте Алигьери', 'Никколо Макиавелли'],
    correctAnswer: 'Джованни Боккаччо',
    acceptableAnswers: ['Джованни Боккаччо', 'Боккаччо'],
    explanation: '«Декамерон» Боккаччо утвердил гуманистические идеалы ренессансной прозы.',
    articleTitle: 'Декамерон',
    articleUrl: 'https://ru.wikipedia.org/wiki/Декамерон',
    difficulty: 'expert',
    category: 'Литература',
    pageviews: 27000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~27k просм/мес)',
  },
  {
    id: 'lit-exp-4',
    question: 'Какой роман Франца Кафки повествует о банковском служащем Йозефе К., внезапно арестованном неведомым правосудием?',
    type: 'multiple_choice',
    options: ['Процесс', 'Замок', 'Америка', 'Превращение'],
    correctAnswer: 'Процесс',
    acceptableAnswers: ['Процесс', 'Der Process'],
    explanation: 'Роман «Процесс» Франца Кафки стал ключевым текстом модернистской литературы о бюрократическом абсурде.',
    articleTitle: 'Процесс (роман)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Процесс_(роман)',
    difficulty: 'expert',
    category: 'Литература',
    pageviews: 31000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~31k просм/мес)',
  },
  {
    id: 'lit-exp-5',
    question: 'Какая антиутопия Евгения Замятина 1920 года о Едином Государстве и нумере Д-503 оказала решающее влияние на «1984» Оруэлла?',
    type: 'open_ended',
    options: ['Мы', 'Котлован', 'О дивный новый мир', 'Чевенгур'],
    correctAnswer: 'Мы',
    acceptableAnswers: ['Мы', 'роман Мы'],
    explanation: 'Роман Замятина «Мы» заложил каноны современной антиутопии с математизированным тоталитарным обществом.',
    articleTitle: 'Мы (роман)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Мы_(роман)',
    difficulty: 'expert',
    category: 'Литература',
    pageviews: 42000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~42k просм/мес)',
  },
];
