import { WikiQuestion } from '../src/types';

// Systematic, high-quality questions for Hard and Expert difficulty levels (Part 2)
// Calibrated distractors: All 4 options belong to the same era/field/category.
export const curatedHardExpertPart2: WikiQuestion[] = [
  // ================= 7. БИОЛОГИЯ (BIOLOGY) =================
  {
    id: 'bio-hard-1',
    question: 'Какие клеточные органеллы эукариот называют «энергетическими станциями», где синтезируется большая часть молекул АТФ?',
    type: 'multiple_choice',
    options: ['Митохондрии', 'Рибосомы', 'Комплекс Гольджи', 'Лизосомы'],
    correctAnswer: 'Митохондрии',
    acceptableAnswers: ['Митохондрии', 'Mitochondria'],
    explanation: 'Митохондрии осуществляют окислительное фосфорилирование и дыхание эукариотической клетки.',
    articleTitle: 'Митохондрия',
    articleUrl: 'https://ru.wikipedia.org/wiki/Митохондрия',
    difficulty: 'hard',
    category: 'Биология',
    pageviews: 31000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~31k просм/мес)',
  },
  {
    id: 'bio-hard-2',
    question: 'Какое семейство хищных млекопитающих включает в себя росомаху, барсука, выдру, соболя и горностая?',
    type: 'multiple_choice',
    options: ['Куньи', 'Виверровые', 'Псовые', 'Енотовые'],
    correctAnswer: 'Куньи',
    acceptableAnswers: ['Куньи', 'Mustelidae'],
    explanation: 'Куньи — одно из самых богатых видами семейств отряда хищных с гибким удлинённым телом.',
    articleTitle: 'Куньи',
    articleUrl: 'https://ru.wikipedia.org/wiki/Куньи',
    difficulty: 'hard',
    category: 'Биология',
    pageviews: 24000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~24k просм/мес)',
  },
  {
    id: 'bio-hard-3',
    question: 'Какой класс членистоногих отличается наличием хелицер, педипальп и четырёх пар ходильных ног?',
    type: 'multiple_choice',
    options: ['Паукообразные', 'Насекомые', 'Ракообразные', 'Губоногие'],
    correctAnswer: 'Паукообразные',
    acceptableAnswers: ['Паукообразные', 'Arachnida'],
    explanation: 'У паукообразных отсутствуют усики, а тело состоит из головогруди и брюшка с 8 ходильными ногами.',
    articleTitle: 'Паукообразные',
    articleUrl: 'https://ru.wikipedia.org/wiki/Паукообразные',
    difficulty: 'hard',
    category: 'Биология',
    pageviews: 28000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~28k просм/мес)',
  },
  {
    id: 'bio-hard-4',
    question: 'Какой австрийский биолог в 1865 году открыл законы наследования признаков при скрещивании сортов гороха?',
    type: 'multiple_choice',
    options: ['Грегор Мендель', 'Томас Морган', 'Хуго де Фриз', 'Карл Линней'],
    correctAnswer: 'Грегор Мендель',
    acceptableAnswers: ['Грегор Мендель', 'Мендель', 'Gregor Mendel'],
    explanation: 'Опыты Менделя на горохе заложили фундамент дискретной генетики задолго до открытия ДНК.',
    articleTitle: 'Мендель, Грегор',
    articleUrl: 'https://ru.wikipedia.org/wiki/Мендель,_Грегор',
    difficulty: 'hard',
    category: 'Биология',
    pageviews: 29000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~29k просм/мес)',
  },
  {
    id: 'bio-hard-5',
    question: 'Какой кровеносный сосуд является самой крупной артерией в теле человека и берёт начало из левого желудочка сердца?',
    type: 'open_ended',
    options: ['Аорта', 'Лёгочный ствол', 'Сонная артерия', 'Подключичная артерия'],
    correctAnswer: 'Аорта',
    acceptableAnswers: ['Аорта', 'Aorta'],
    explanation: 'Аорта распределяет насыщенную кислородом кровь по всему большому кругу кровообращения.',
    articleTitle: 'Аорта',
    articleUrl: 'https://ru.wikipedia.org/wiki/Аорта',
    difficulty: 'hard',
    category: 'Биология',
    pageviews: 32000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~32k просм/мес)',
  },

  // Expert Биология
  {
    id: 'bio-exp-1',
    question: 'Какой циклический каскад реакций окисления ацетил-КоА в митохондриях является узловым этапом клеточного дыхания?',
    type: 'multiple_choice',
    options: ['Цикл Кребса', 'Цикл Кальвина', 'Орнитиновый цикл', 'Цикл Кори'],
    correctAnswer: 'Цикл Кребса',
    acceptableAnswers: ['Цикл Кребса', 'Кребс', 'Цикл трикарбоновых кислот'],
    explanation: 'Ханс Кребс описал цикл трикарбоновых кислот в 1937 году и был удостоен Нобелевской премии.',
    articleTitle: 'Цикл трикарбоновых кислот',
    articleUrl: 'https://ru.wikipedia.org/wiki/Цикл_трикарбоновых_кислот',
    difficulty: 'expert',
    category: 'Биология',
    pageviews: 26000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~26k просм/мес)',
  },
  {
    id: 'bio-exp-2',
    question: 'Какой растворимый белок плазмы крови под действием тромбина полимеризуется в нерастворимый фибрин, формируя тромб?',
    type: 'multiple_choice',
    options: ['Фибриноген', 'Альбумин', 'Протромбин', 'Трансферрин'],
    correctAnswer: 'Фибриноген',
    acceptableAnswers: ['Фибриноген', 'Fibrinogen'],
    explanation: 'Фибриноген синтезируется в печени и является ключевым фактором I свёртывающей системы крови.',
    articleTitle: 'Фибриноген',
    articleUrl: 'https://ru.wikipedia.org/wiki/Фибриноген',
    difficulty: 'expert',
    category: 'Биология',
    pageviews: 14000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~14k просм/мес)',
  },
  {
    id: 'bio-exp-3',
    question: 'Какое пиримидиновое азотистое основание заменяет тимин в молекулах РНК и образует пару с аденином?',
    type: 'multiple_choice',
    options: ['Урацил', 'Гуанин', 'Цитозин', 'Инозин'],
    correctAnswer: 'Урацил',
    acceptableAnswers: ['Урацил', 'Uracil'],
    explanation: 'Урацил комплементарен аденину и отличается от тимина отсутствием метильной группы.',
    articleTitle: 'Урацил',
    articleUrl: 'https://ru.wikipedia.org/wiki/Урацил',
    difficulty: 'expert',
    category: 'Биология',
    pageviews: 18000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~18k просм/мес)',
  },
  {
    id: 'bio-exp-4',
    question: 'Какая железа внутренней секреции синтезирует гормон мелатонин, регулирующий циклы сна и бодрствования человека?',
    type: 'multiple_choice',
    options: ['Эпифиз (шишковидное тело)', 'Гипофиз', 'Щитовидная железа', 'Надпочечники'],
    correctAnswer: 'Эпифиз (шишковидное тело)',
    acceptableAnswers: ['Эпифиз', 'Шишковидное тело', 'Эпифиз (шишковидное тело)'],
    explanation: 'Эпифиз реагирует на уровень освещённости и увеличивает секрецию мелатонина в тёмное время суток.',
    articleTitle: 'Эпифиз',
    articleUrl: 'https://ru.wikipedia.org/wiki/Эпифиз',
    difficulty: 'expert',
    category: 'Биология',
    pageviews: 22000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~22k просм/мес)',
  },
  {
    id: 'bio-exp-5',
    question: 'Как называется особый тип редукционного деления эукариот, приводящий к уменьшению числа хромосом вдвое при формировании гамет?',
    type: 'open_ended',
    options: ['Мейоз', 'Митоз', 'Амитоз', 'Шизогония'],
    correctAnswer: 'Мейоз',
    acceptableAnswers: ['Мейоз', 'Meiosis'],
    explanation: 'Мейоз состоит из двух последовательных делений и обеспечивает генетическое разнообразие через кроссинговер.',
    articleTitle: 'Мейоз',
    articleUrl: 'https://ru.wikipedia.org/wiki/Мейоз',
    difficulty: 'expert',
    category: 'Биология',
    pageviews: 31000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~31k просм/мес)',
  },

  // ================= 8. ИСКУССТВО (ART) =================
  {
    id: 'art-hard-1',
    question: 'Какой русский живописец-передвижник создал масштабные исторические полотна «Утро стрелецкой казни» и «Боярыня Морозова»?',
    type: 'multiple_choice',
    options: ['Василий Суриков', 'Илья Репин', 'Виктор Васнецов', 'Иван Крамской'],
    correctAnswer: 'Василий Суриков',
    acceptableAnswers: ['Василий Суриков', 'Суриков'],
    explanation: 'Василий Суриков виртуозно передавал трагические переломные моменты русской национальной истории.',
    articleTitle: 'Суриков, Василий Иванович',
    articleUrl: 'https://ru.wikipedia.org/wiki/Суриков,_Василий_Иванович',
    difficulty: 'hard',
    category: 'Искусство',
    pageviews: 28000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~28k просм/мес)',
  },
  {
    id: 'art-hard-2',
    question: 'Какая картина Клода Моне 1872 года с видом на гавань Гавра на рассвете дала название направлению «импрессионизм»?',
    type: 'multiple_choice',
    options: ['Впечатление. Восходящее солнце', 'Водяные лилии', 'Руанский собор', 'Бульвар Капуцинок'],
    correctAnswer: 'Впечатление. Восходящее солнце',
    acceptableAnswers: ['Впечатление. Восходящее солнце', 'Впечатление', 'Impression, soleil levant'],
    explanation: 'Критик Луи Леруа уничижительно окрестил выставку «импрессионистами» по названию этой картины Моне.',
    articleTitle: 'Впечатление. Восходящее солнце',
    articleUrl: 'https://ru.wikipedia.org/wiki/Впечатление._Восходящее_солнце',
    difficulty: 'hard',
    category: 'Искусство',
    pageviews: 32000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~32k просм/мес)',
  },
  {
    id: 'art-hard-3',
    question: 'Какой нидерландский художник Северного Возрождения написал загадочный алтарный триптих «Сад земных наслаждений»?',
    type: 'multiple_choice',
    options: ['Иероним Босх', 'Питер Брейгель Старший', 'Ян ван Эйк', 'Рогир ван дер Вейден'],
    correctAnswer: 'Иероним Босх',
    acceptableAnswers: ['Иероним Босх', 'Босх', 'Hieronymus Bosch'],
    explanation: 'Иероним Босх наполнил триптих сложнейшей средневековой аллегорией грехопадения человечества.',
    articleTitle: 'Сад земных наслаждений',
    articleUrl: 'https://ru.wikipedia.org/wiki/Сад_земных_наслаждений',
    difficulty: 'hard',
    category: 'Искусство',
    pageviews: 39000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~39k просм/мес)',
  },
  {
    id: 'art-hard-4',
    question: 'Какой архитектор и скульптор римского барокко спроектировал колоннаду площади Святого Петра и статую «Экстаз святой Терезы»?',
    type: 'multiple_choice',
    options: ['Джованни Лоренцо Бернини', 'Франческо Борромини', 'Пьетро да Кортона', 'Карло Мадерна'],
    correctAnswer: 'Джованни Лоренцо Бернини',
    acceptableAnswers: ['Джованни Лоренцо Бернини', 'Бернини', 'Bernini'],
    explanation: 'Джан Лоренцо Бернини определил монументальный и пластический облик Рима эпохи барокко.',
    articleTitle: 'Бернини, Джованни Лоренцо',
    articleUrl: 'https://ru.wikipedia.org/wiki/Бернини,_Джованни_Лоренцо',
    difficulty: 'hard',
    category: 'Искусство',
    pageviews: 23000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~23k просм/мес)',
  },
  {
    id: 'art-hard-5',
    question: 'Какой русский художник-пейзажист написал знаменитое полотно «Утро в сосновом лесу» (фигуры медведей выполнил Савицкий)?',
    type: 'open_ended',
    options: ['Иван Шишкин', 'Исаак Левитан', 'Алексей Саврасов', 'Архип Куинджи'],
    correctAnswer: 'Иван Шишкин',
    acceptableAnswers: ['Иван Шишкин', 'Шишкин'],
    explanation: 'Иван Шишкин был непревзойдённым мастером русской лесной природы и ботанической точности.',
    articleTitle: 'Утро в сосновом лесу',
    articleUrl: 'https://ru.wikipedia.org/wiki/Утро_в_сосновом_лесу',
    difficulty: 'hard',
    category: 'Искусство',
    pageviews: 36000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~36k просм/мес)',
  },

  // Expert Искусство
  {
    id: 'art-exp-1',
    question: 'Какой испанский живописец XVII века на картине «Менины» изобразил юную инфанту Маргариту и самого себя у мольберта?',
    type: 'multiple_choice',
    options: ['Диего Веласкес', 'Франсиско де Сурбаран', 'Бартоломе Эстебан Мурильо', 'Эль Греко'],
    correctAnswer: 'Диего Веласкес',
    acceptableAnswers: ['Диего Веласкес', 'Веласкес', 'Diego Velázquez'],
    explanation: '«Менины» Веласкеса — один из сложнейших живописных шедевров о природе взгляда и пространства холста.',
    articleTitle: 'Менины',
    articleUrl: 'https://ru.wikipedia.org/wiki/Менины',
    difficulty: 'expert',
    category: 'Искусство',
    pageviews: 31000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~31k просм/мес)',
  },
  {
    id: 'art-exp-2',
    question: 'В каком стиле между Высоким Возрождением и барокко с удлинёнными пропорциями и виртуозной манерой творил Пармиджанино?',
    type: 'multiple_choice',
    options: ['Маньеризм', 'Рококо', 'Классицизм', 'Неоготика'],
    correctAnswer: 'Маньеризм',
    acceptableAnswers: ['Маньеризм', 'Mannerism'],
    explanation: 'Маньеризм культивировал изящество позы, напряжённую спираль и отказ от строгой ренессансной гармонии.',
    articleTitle: 'Маньеризм',
    articleUrl: 'https://ru.wikipedia.org/wiki/Маньеризм',
    difficulty: 'expert',
    category: 'Искусство',
    pageviews: 24000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~24k просм/мес)',
  },
  {
    id: 'art-exp-3',
    question: 'Какой итальянский новатор живописи барокко создал полотна «Призвание апостола Матфея» с драматичным светотеневым контрастом (кьяроскуро)?',
    type: 'multiple_choice',
    options: ['Караваджо', 'Аннибале Карраччи', 'Гвидо Рени', 'Артемизия Джентилески'],
    correctAnswer: 'Караваджо',
    acceptableAnswers: ['Караваджо', 'Caravaggio', 'Микеланджело Меризи да Караваджо'],
    explanation: 'Караваджо произвёл переворот в живописи, введя грубый реализм и направленный луч света из темноты (тенебризм).',
    articleTitle: 'Караваджо',
    articleUrl: 'https://ru.wikipedia.org/wiki/Караваджо',
    difficulty: 'expert',
    category: 'Искусство',
    pageviews: 37000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~37k просм/мес)',
  },
  {
    id: 'art-exp-4',
    question: 'Какой шедевр византийского зодчества VI века в Константинополе возвели зодчие Исидор Милетский и Анфимий из Тралл?',
    type: 'multiple_choice',
    options: ['Собор Святой Софии', 'Церковь Хора', 'Церковь Сергия и Вакха', 'Собор Святой Ирины'],
    correctAnswer: 'Собор Святой Софии',
    acceptableAnswers: ['Собор Святой Софии', 'Айя-София', 'Святая София'],
    explanation: 'Купол Святой Софии диаметром 31 метр парит над 40 арочными окнами, символизируя небесный свод.',
    articleTitle: 'Собор Святой Софии (Константинополь)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Собор_Святой_Софии_(Константинополь)',
    difficulty: 'expert',
    category: 'Искусство',
    pageviews: 48000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~48k просм/мес)',
  },
  {
    id: 'art-exp-5',
    question: 'Какой австрийский лидер венского сецессиона написал сияющую сусальным золотом картину «Поцелуй» (1907–1908)?',
    type: 'open_ended',
    options: ['Густав Климт', 'Эгон Шиле', 'Оскар Кокошка', 'Коломан Мозер'],
    correctAnswer: 'Густав Климт',
    acceptableAnswers: ['Густав Климт', 'Климт', 'Gustav Klimt'],
    explanation: '«Поцелуй» Густава Климта стал вершиной его «золотого периода» в стиле венского модерна.',
    articleTitle: 'Поцелуй (картина Климта)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Поцелуй_(картина_Климта)',
    difficulty: 'expert',
    category: 'Искусство',
    pageviews: 35000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~35k просм/мес)',
  },

  // ================= 9. КИНО (CINEMA) =================
  {
    id: 'mov-hard-1',
    question: 'Какой итальянский кинорежиссёр снял автобиографический фильм «8½» (1963) и драму «Сладкая жизнь» с Марчелло Мастроянни?',
    type: 'multiple_choice',
    options: ['Федерико Феллини', 'Микеланджело Антониони', 'Лукино Висконти', 'Бернардо Бертолуччи'],
    correctAnswer: 'Федерико Феллини',
    acceptableAnswers: ['Федерико Феллини', 'Феллини'],
    explanation: 'Федерико Феллини создал неповторимую барочно-сновидческую эстетику кинематографа.',
    articleTitle: 'Феллини, Федерико',
    articleUrl: 'https://ru.wikipedia.org/wiki/Феллини,_Федерико',
    difficulty: 'hard',
    category: 'Кино',
    pageviews: 29000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~29k просм/мес)',
  },
  {
    id: 'mov-hard-2',
    question: 'В каком фантастическом фильме Стэнли Кубрика 1968 года кораблём управляет свихнувшийся бортовой интеллект HAL 9000?',
    type: 'multiple_choice',
    options: ['2001 год: Космическая одиссея', 'Солярис', 'Заводной апельсин', 'Бегущий по лезвию'],
    correctAnswer: '2001 год: Космическая одиссея',
    acceptableAnswers: ['2001 год: Космическая одиссея', 'Космическая одиссея', '2001: A Space Odyssey'],
    explanation: 'Фильм Стэнли Кубрика совершил революцию в практических спецэффектах и философии sci-fi кино.',
    articleTitle: '2001 год: Космическая одиссея (фильм)',
    articleUrl: 'https://ru.wikipedia.org/wiki/2001_год:_Космическая_одиссея_(фильм)',
    difficulty: 'hard',
    category: 'Кино',
    pageviews: 36000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~36k просм/мес)',
  },
  {
    id: 'mov-hard-3',
    question: 'Какой советский режиссёр поставил экзистенциальные кинокартины «Андрей Рублёв», «Зеркало» и «Сталкер»?',
    type: 'multiple_choice',
    options: ['Андрей Тарковский', 'Сергей Параджанов', 'Элем Климов', 'Марлен Хуциев'],
    correctAnswer: 'Андрей Тарковский',
    acceptableAnswers: ['Андрей Тарковский', 'Тарковский'],
    explanation: 'Андрей Тарковский разработал концепцию «запечатлённого времени» с медитативными длинными планами.',
    articleTitle: 'Тарковский, Андрей Арсеньевич',
    articleUrl: 'https://ru.wikipedia.org/wiki/Тарковский,_Андрей_Арсеньевич',
    difficulty: 'hard',
    category: 'Кино',
    pageviews: 38000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~38k просм/мес)',
  },
  {
    id: 'mov-hard-4',
    question: 'Какой японский кинорежиссёр снял классические шедевры «Семь самураев» (1954), «Расёмон» и «Ран»?',
    type: 'multiple_choice',
    options: ['Акира Куросава', 'Ясудзиро Одзу', 'Кэндзи Мидзогути', 'Масаки Кобаяси'],
    correctAnswer: 'Акира Куросава',
    acceptableAnswers: ['Акира Куросава', 'Куросава', 'Akira Kurosawa'],
    explanation: 'Фильмы Акиры Куросавы оказали колоссальное влияние на мировую режиссуру, от вестернов до «Звёздных войн».',
    articleTitle: 'Куросава, Акира',
    articleUrl: 'https://ru.wikipedia.org/wiki/Куросава,_Акира',
    difficulty: 'hard',
    category: 'Кино',
    pageviews: 31000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~31k просм/мес)',
  },
  {
    id: 'mov-hard-5',
    question: 'Какой новозеландский режиссёр поставил оскароносную кинематографическую трилогию «Властелин колец»?',
    type: 'open_ended',
    options: ['Питер Джексон', 'Джордж Лукас', 'Джеймс Кэмерон', 'Ридли Скотт'],
    correctAnswer: 'Питер Джексон',
    acceptableAnswers: ['Питер Джексон', 'Джексон', 'Peter Jackson'],
    explanation: 'Трилогия Питера Джексона завоевала 17 премий «Оскар», включая 11 статуэток для «Возвращения короля».',
    articleTitle: 'Властелин колец (кинотрилогия)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Властелин_колец_(кинотрилогия)',
    difficulty: 'hard',
    category: 'Кино',
    pageviews: 44000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~44k просм/мес)',
  },

  // Expert Кино
  {
    id: 'mov-exp-1',
    question: 'Какой режиссёр французской новой волны снял манифест направления «На последнем дыхании» (1960) с Бельмондо?',
    type: 'multiple_choice',
    options: ['Жан-Люк Годар', 'Франсуа Трюффо', 'Клод Шаброль', 'Эрик Ромер'],
    correctAnswer: 'Жан-Люк Годар',
    acceptableAnswers: ['Жан-Люк Годар', 'Годар', 'Jean-Luc Godard'],
    explanation: 'Жан-Люк Годар сломал классический монтаж введением джамп-катов и съемкой ручной камерой на улицах Парижа.',
    articleTitle: 'На последнем дыхании (фильм, 1960)',
    articleUrl: 'https://ru.wikipedia.org/wiki/На_последнем_дыхании_(фильм,_1960)',
    difficulty: 'expert',
    category: 'Кино',
    pageviews: 22000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~22k просм/мес)',
  },
  {
    id: 'mov-exp-2',
    question: 'В каком фильме Ингмара Бергмана 1957 года средневековый рыцарь Антониус Блок играет партию в шахматы со Смертью?',
    type: 'multiple_choice',
    options: ['Седьмая печать', 'Земляничная поляна', 'Персона', 'Источник'],
    correctAnswer: 'Седьмая печать',
    acceptableAnswers: ['Седьмая печать', 'Det sjunde inseglet'],
    explanation: '«Седьмая печать» Ингмара Бергмана стала хрестоматийным философским фильмом об утрате веры.',
    articleTitle: 'Седьмая печать',
    articleUrl: 'https://ru.wikipedia.org/wiki/Седьмая_печать',
    difficulty: 'expert',
    category: 'Кино',
    pageviews: 28000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~28k просм/мес)',
  },
  {
    id: 'mov-exp-3',
    question: 'Какой немецкий кинорежиссёр эпохи экспрессионизма создал монументальную антиутопию «Метрополис» (1927)?',
    type: 'multiple_choice',
    options: ['Фриц Ланг', 'Фридрих Вильгельм Мурнау', 'Роберт Вине', 'Георг Вильгельм Пабст'],
    correctAnswer: 'Фриц Ланг',
    acceptableAnswers: ['Фриц Ланг', 'Ланг', 'Fritz Lang'],
    explanation: 'Фриц Ланг создал грандиозные визуальные образы футуристического мегаполиса и робота-женщины Марии.',
    articleTitle: 'Метрополис (фильм)',
    articleUrl: 'https://ru.wikipedia.org/wiki/Метрополис_(фильм)',
    difficulty: 'expert',
    category: 'Кино',
    pageviews: 33000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~33k просм/мес)',
  },
  {
    id: 'mov-exp-4',
    question: 'Какой советский кинооператор снял «Летят журавли» (1957) Михаила Калатозова, изобретя вихревые круговые движения камеры?',
    type: 'multiple_choice',
    options: ['Сергей Урусевский', 'Вадим Юсов', 'Эдуард Тиссэ', 'Георгий Рерберг'],
    correctAnswer: 'Сергей Урусевский',
    acceptableAnswers: ['Сергей Урусевский', 'Урусевский'],
    explanation: 'Сергей Урусевский получил специальный приз Каннского фестиваля за непревзойдённую экспрессию съёмки.',
    articleTitle: 'Урусевский, Сергей Павлович',
    articleUrl: 'https://ru.wikipedia.org/wiki/Урусевский,_Сергей_Павлович',
    difficulty: 'expert',
    category: 'Кино',
    pageviews: 11000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~11k просм/мес)',
  },
  {
    id: 'mov-exp-5',
    question: 'Какой польский режиссёр поставил кинематографическую трилогию «Три цвета» («Синий», «Белый», «Красный»)?',
    type: 'open_ended',
    options: ['Кшиштоф Кесьлёвский', 'Анджей Вайда', 'Роман Полански', 'Кшиштоф Занусси'],
    correctAnswer: 'Кшиштоф Кесьлёвский',
    acceptableAnswers: ['Кшиштоф Кесьлёвский', 'Кесьлёвский', 'Krzysztof Kieślowski'],
    explanation: 'Кшиштоф Кесьлёвский посвятил трилогию цветам французского флага и девизу «Свобода, Равенство, Братство».',
    articleTitle: 'Кесьлёвский, Кшиштоф',
    articleUrl: 'https://ru.wikipedia.org/wiki/Кесьлёвский,_Кшиштоф',
    difficulty: 'expert',
    category: 'Кино',
    pageviews: 18000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~18k просм/мес)',
  },

  // ================= 10. СПОРТ (SPORTS) =================
  {
    id: 'spt-hard-1',
    question: 'В какой стране в 1930 году состоялся самый первый чемпионат мира по футболу ФИФА, где победили хозяева турнира?',
    type: 'multiple_choice',
    options: ['Уругвай', 'Бразилия', 'Италия', 'Аргентина'],
    correctAnswer: 'Уругвай',
    acceptableAnswers: ['Уругвай', 'Uruguay'],
    explanation: 'Уругвай выиграл домашний чемпионат мира 1930 года на стадионе «Сентенарио», победив Аргентину 4:2.',
    articleTitle: 'Чемпионат мира по футболу 1930',
    articleUrl: 'https://ru.wikipedia.org/wiki/Чемпионат_мира_по_футболу_1930',
    difficulty: 'hard',
    category: 'Спорт',
    pageviews: 29000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~29k просм/мес)',
  },
  {
    id: 'spt-hard-2',
    question: 'Какой легкоатлет стал первым человеком в истории, преодолевшим 6-метровую планку в прыжках с шестом (1985)?',
    type: 'multiple_choice',
    options: ['Сергей Бубка', 'Родион Гатауллин', 'Максим Тарасов', 'Арман Дюплантис'],
    correctAnswer: 'Сергей Бубка',
    acceptableAnswers: ['Сергей Бубка', 'Бубка'],
    explanation: 'Сергей Бубка установил 35 мировых рекордов и покорил 6,00 метров в Париже 13 июля 1985 года.',
    articleTitle: 'Бубка, Сергей Назарович',
    articleUrl: 'https://ru.wikipedia.org/wiki/Бубка,_Сергей_Назарович',
    difficulty: 'hard',
    category: 'Спорт',
    pageviews: 28000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~28k просм/мес)',
  },
  {
    id: 'spt-hard-3',
    question: 'Какой канадский хоккеист по прозвищу «Великий» набрал рекордные 2857 очков и забил 894 шайбы в регулярных сезонах НХЛ?',
    type: 'multiple_choice',
    options: ['Уэйн Гретцки', 'Марио Лемьё', 'Горди Хоу', 'Бобби Орр'],
    correctAnswer: 'Уэйн Гретцки',
    acceptableAnswers: ['Уэйн Гретцки', 'Гретцки', 'Wayne Gretzky'],
    explanation: 'Номер 99 Уэйна Гретцки выведен из обращения во всей Национальной хоккейной лиге.',
    articleTitle: 'Гретцки, Уэйн',
    articleUrl: 'https://ru.wikipedia.org/wiki/Гретцки,_Уэйн',
    difficulty: 'hard',
    category: 'Спорт',
    pageviews: 37000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~37k просм/мес)',
  },
  {
    id: 'spt-hard-4',
    question: 'В каком виде спорта разыгрывается старейший престижный командный трофей «Кубок Дэвиса», учреждённый в 1900 году?',
    type: 'multiple_choice',
    options: ['Теннис', 'Гольф', 'Парусный спорт', 'Крикет'],
    correctAnswer: 'Теннис',
    acceptableAnswers: ['Теннис', 'Tennis'],
    explanation: 'Кубок Дэвиса является крупнейшим ежегодным командным турниром в мужском теннисе.',
    articleTitle: 'Кубок Дэвиса',
    articleUrl: 'https://ru.wikipedia.org/wiki/Кубок_Дэвиса',
    difficulty: 'hard',
    category: 'Спорт',
    pageviews: 26000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~26k просм/мес)',
  },
  {
    id: 'spt-hard-5',
    question: 'Какой единственный в истории футбольный вратарь удостоился престижного приза «Золотой мяч» (в 1963 году)?',
    type: 'open_ended',
    options: ['Лев Яшин', 'Дино Дзофф', 'Гордон Бэнкс', 'Зепп Майер'],
    correctAnswer: 'Лев Яшин',
    acceptableAnswers: ['Лев Яшин', 'Яшин'],
    explanation: 'Вратарь московского «Динамо» и сборной СССР Лев Яшин получил «Золотой мяч» за выдающуюся игру на ленточке и выходах.',
    articleTitle: 'Яшин, Лев Иванович',
    articleUrl: 'https://ru.wikipedia.org/wiki/Яшин,_Лев_Иванович',
    difficulty: 'hard',
    category: 'Спорт',
    pageviews: 45000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~45k просм/мес)',
  },

  // Expert Спорт
  {
    id: 'spt-exp-1',
    question: 'Какой чехословацкий стайер на Олимпиаде 1952 года в Хельсинки выиграл золото на 5000 м, 10 000 м и в марафоне?',
    type: 'multiple_choice',
    options: ['Эмиль Затопек', 'Пааво Нурми', 'Лассе Вирен', 'Хайле Гебреселассие'],
    correctAnswer: 'Эмиль Затопек',
    acceptableAnswers: ['Эмиль Затопек', 'Затопек', 'Emil Zátopek'],
    explanation: 'Эмиль Затопек сотворил уникальный тройной триумф, пробежав свой первый марафон в жизни на олимпийской трассе.',
    articleTitle: 'Затопек, Эмиль',
    articleUrl: 'https://ru.wikipedia.org/wiki/Затопек,_Эмиль',
    difficulty: 'expert',
    category: 'Спорт',
    pageviews: 18000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~18k просм/мес)',
  },
  {
    id: 'spt-exp-2',
    question: 'Какой американский прыгун на Олимпиаде 1968 года в Мехико установил мировой рекорд в прыжках в длину 8,90 м?',
    type: 'multiple_choice',
    options: ['Боб Бимон', 'Карл Льюис', 'Майк Пауэлл', 'Джесси Оуэнс'],
    correctAnswer: 'Боб Бимон',
    acceptableAnswers: ['Боб Бимон', 'Бимон', 'Bob Beamon'],
    explanation: '«Прыжок в XXI век» Боба Бимона превзошёл прежний мировой рекорд сразу на 55 сантиметров.',
    articleTitle: 'Бимон, Боб',
    articleUrl: 'https://ru.wikipedia.org/wiki/Бимон,_Боб',
    difficulty: 'expert',
    category: 'Спорт',
    pageviews: 16000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~16k просм/мес)',
  },
  {
    id: 'spt-exp-3',
    question: 'Какая 14-летняя румынская гимнастка на Олимпиаде 1976 года в Монреале первой в истории получила идеальную оценку 10,0?',
    type: 'multiple_choice',
    options: ['Надя Команечи', 'Нелли Ким', 'Ольга Корбут', 'Людмила Турищева'],
    correctAnswer: 'Надя Команечи',
    acceptableAnswers: ['Надя Команечи', 'Команечи', 'Nadia Comăneci'],
    explanation: 'Табло в Монреале не было рассчитано на 10 баллов и показало «1.00», войдя в историю мирового спорта.',
    articleTitle: 'Команечи, Надя',
    articleUrl: 'https://ru.wikipedia.org/wiki/Команечи,_Надя',
    difficulty: 'expert',
    category: 'Спорт',
    pageviews: 29000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~29k просм/мес)',
  },
  {
    id: 'spt-exp-4',
    question: 'Какой финский бегун по прозвищу «Летучий финн» завоевал 9 золотых и 3 серебряные олимпийские медали в 1920-х годах?',
    type: 'multiple_choice',
    options: ['Пааво Нурми', 'Вилле Ритола', 'Ханнес Колехмайнен', 'Волмари Исо-Холло'],
    correctAnswer: 'Пааво Нурми',
    acceptableAnswers: ['Пааво Нурми', 'Нурми', 'Paavo Nurmi'],
    explanation: 'Пааво Нурми бежал с секундомером в руке и установил 22 официальных мировых рекорда.',
    articleTitle: 'Нурми, Пааво',
    articleUrl: 'https://ru.wikipedia.org/wiki/Нурми,_Пааво',
    difficulty: 'expert',
    category: 'Спорт',
    pageviews: 21000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~21k просм/мес)',
  },
  {
    id: 'spt-exp-5',
    question: 'Какой бразильский автогонщик, трёхкратный чемпион «Формулы-1», трагически погиб в повороте Тамбурелло в Имоле в 1994 году?',
    type: 'open_ended',
    options: ['Айртон Сенна', 'Нельсон Пике', 'Ален Прост', 'Найджел Мэнселл'],
    correctAnswer: 'Айртон Сенна',
    acceptableAnswers: ['Айртон Сенна', 'Сенна', 'Ayrton Senna'],
    explanation: 'Айртон Сенна («Волшебник») считался непревзойдённым мастером квалификаций и дождевых гонок.',
    articleTitle: 'Сенна, Айртон',
    articleUrl: 'https://ru.wikipedia.org/wiki/Сенна,_Айртон',
    difficulty: 'expert',
    category: 'Спорт',
    pageviews: 43000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~43k просм/мес)',
  },

  // ================= 11. МИФОЛОГИЯ (MYTHOLOGY) =================
  {
    id: 'myt-hard-1',
    question: 'Как в скандинавской мифологии зовут мирового змея, рождённого Локи, опоясывающего Мидгард и кусающего свой хвост?',
    type: 'multiple_choice',
    options: ['Ёрмунганд', 'Нидхёгг', 'Фафнир', 'Фенрир'],
    correctAnswer: 'Ёрмунганд',
    acceptableAnswers: ['Ёрмунганд', 'Мидгардсорм', 'Jörmungandr'],
    explanation: 'В Рагнарёк Тор сразит Ёрмунганда своим молотом Мьёльниром, но погибнет от его яда, сделав девять шагов.',
    articleTitle: 'Ёрмунганд',
    articleUrl: 'https://ru.wikipedia.org/wiki/Ёрмунганд',
    difficulty: 'hard',
    category: 'Мифология',
    pageviews: 31000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~31k просм/мес)',
  },
  {
    id: 'myt-hard-2',
    question: 'Какой древнегреческий музыкант спустился в Аид за возлюбленной Эвридикой, очаровав владыку преисподней пением под лиру?',
    type: 'multiple_choice',
    options: ['Орфей', 'Тесей', 'Геракл', 'Персей'],
    correctAnswer: 'Орфей',
    acceptableAnswers: ['Орфей', 'Orpheus'],
    explanation: 'Орфей нарушил запрет не оборачиваться на выходе из подземного царства и навсегда потерял Эвридику.',
    articleTitle: 'Орфей',
    articleUrl: 'https://ru.wikipedia.org/wiki/Орфей',
    difficulty: 'hard',
    category: 'Мифология',
    pageviews: 34000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~34k просм/мес)',
  },
  {
    id: 'myt-hard-3',
    question: 'В древнеегипетской мифологии какой шакалоголовый бог взвешивал сердце умершего на весах против страусиного пера богини Маат?',
    type: 'multiple_choice',
    options: ['Анубис', 'Осирис', 'Тот', 'Гор'],
    correctAnswer: 'Анубис',
    acceptableAnswers: ['Анубис', 'Anubis'],
    explanation: 'Анубис — проводник душ в загробное царство Дуат и покровитель бальзамирования.',
    articleTitle: 'Анубис',
    articleUrl: 'https://ru.wikipedia.org/wiki/Анубис',
    difficulty: 'hard',
    category: 'Мифология',
    pageviews: 41000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~41k просм/мес)',
  },
  {
    id: 'myt-hard-4',
    question: 'Как в славянском языческом пантеоне зовут «скотьего бога», покровителя скота, богатства и тайных сил, противника Перуна?',
    type: 'multiple_choice',
    options: ['Велес (Волос)', 'Даждьбог', 'Сварог', 'Стрибог'],
    correctAnswer: 'Велес (Волос)',
    acceptableAnswers: ['Велес', 'Волос', 'Велес (Волос)'],
    explanation: 'Велес олицетворял нижний мир, плодородие и богатство в противопоставлении громовержцу Перуну.',
    articleTitle: 'Велес',
    articleUrl: 'https://ru.wikipedia.org/wiki/Велес',
    difficulty: 'hard',
    category: 'Мифология',
    pageviews: 36000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~36k просм/мес)',
  },
  {
    id: 'myt-hard-5',
    question: 'Какой верховный бог скандинавского пантеона пожертвовал своим глазом великану Мимиру за глоток из источника мудрости?',
    type: 'open_ended',
    options: ['Один', 'Тор', 'Тюр', 'Хеймдалль'],
    correctAnswer: 'Один',
    acceptableAnswers: ['Один', 'Odin'],
    explanation: 'Один отдал глаз за знание рун и сокровенную мудрость у корней мирового ясеня Иггдрасиль.',
    articleTitle: 'Один',
    articleUrl: 'https://ru.wikipedia.org/wiki/Один',
    difficulty: 'hard',
    category: 'Мифология',
    pageviews: 48000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~48k просм/мес)',
  },

  // Expert Мифология
  {
    id: 'myt-exp-1',
    question: 'Как в скандинавской мифологии зовут восьминогого жеребца верховного бога Одина, рождённого Локи?',
    type: 'multiple_choice',
    options: ['Слейпнир', 'Гульфакси', 'Скинфакси', 'Грани'],
    correctAnswer: 'Слейпнир',
    acceptableAnswers: ['Слейпнир', 'Sleipnir'],
    explanation: 'Слейпнир способен мчаться быстрее ветра по небу, земле и морским водам.',
    articleTitle: 'Слейпнир',
    articleUrl: 'https://ru.wikipedia.org/wiki/Слейпнир',
    difficulty: 'expert',
    category: 'Мифология',
    pageviews: 22000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~22k просм/мес)',
  },
  {
    id: 'myt-exp-2',
    question: 'Какая шумерская богиня плодородия и любви спустилась в преисподнюю (Кур) к сестре Эрешкигаль через семь врат?',
    type: 'multiple_choice',
    options: ['Инанна (Иштар)', 'Нинхурсаг', 'Тиамат', 'Бау'],
    correctAnswer: 'Инанна (Иштар)',
    acceptableAnswers: ['Инанна', 'Иштар', 'Инанна (Иштар)'],
    explanation: '«Нисхождение Инанны в нижний мир» — один из древнейших мифологических текстов в истории человечества.',
    articleTitle: 'Инанна',
    articleUrl: 'https://ru.wikipedia.org/wiki/Инанна',
    difficulty: 'expert',
    category: 'Мифология',
    pageviews: 29000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~29k просм/мес)',
  },
  {
    id: 'myt-exp-3',
    question: 'В индийской мифологии какой царь птиц служит ездовым животным (ваханой) бога Вишну и враждует со змеями-нага?',
    type: 'multiple_choice',
    options: ['Гаруда', 'Хануман', 'Нанди', 'Айравата'],
    correctAnswer: 'Гаруда',
    acceptableAnswers: ['Гаруда', 'Garuda'],
    explanation: 'Гаруда изображается получеловеком-полуорлом и является национальным символом Индонезии и Таиланда.',
    articleTitle: 'Гаруда',
    articleUrl: 'https://ru.wikipedia.org/wiki/Гаруда',
    difficulty: 'expert',
    category: 'Мифология',
    pageviews: 26000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~26k просм/мес)',
  },
  {
    id: 'myt-exp-4',
    question: 'Какой коринфский царь за обман богов был обречён в Аиде вечно вкатывать на вершину горы срывающийся камень?',
    type: 'multiple_choice',
    options: ['Сизиф', 'Тантал', 'Иксион', 'Салмоней'],
    correctAnswer: 'Сизиф',
    acceptableAnswers: ['Сизиф', 'Sisyphus'],
    explanation: '«Сизифов труд» стал крылатым выражением, символизирующим бесконечную и безрезультатную работу.',
    articleTitle: 'Сизиф',
    articleUrl: 'https://ru.wikipedia.org/wiki/Сизиф',
    difficulty: 'expert',
    category: 'Мифология',
    pageviews: 31000,
    popularityTier: 'top_tier',
    popularityLabel: 'Топ-статья Википедии (~31k просм/мес)',
  },
  {
    id: 'myt-exp-5',
    question: 'В карело-финском эпосе «Калевала» какая чудесная мельница, выкованная кузнецом Ильмариненом, мелет муку, соль и золото?',
    type: 'open_ended',
    options: ['Сампо', 'Кантеле', 'Вяйнямёйнен', 'Похъёла'],
    correctAnswer: 'Сампо',
    acceptableAnswers: ['Сампо', 'Sampo'],
    explanation: 'Мельница Сампо служила источником изобилия и благополучия в эпосе «Калевала».',
    articleTitle: 'Сампо',
    articleUrl: 'https://ru.wikipedia.org/wiki/Сампо',
    difficulty: 'expert',
    category: 'Мифология',
    pageviews: 21000,
    popularityTier: 'high',
    popularityLabel: 'Высокая популярность (~21k просм/мес)',
  },
];
